PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ond: <https://data.hetarchief.be/id/onderwijs/>
PREFIX ovak: <https://data.hetarchief.be/id/onderwijs/vak/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
  ?concept skos:related ?thema;
      skos:related ?graad.
}
WHERE {
    BIND ('https://data.hetarchief.be/id/onderwijs/' AS ?ns)
    BIND (ENCODE_FOR_URI(LCASE(
        REPLACE(
            IF(  
                CONTAINS(?b, " ("),
                STRBEFORE(?b," ("),
                ?b
            )
            , " ", "-"))) AS ?key)
    BIND (URI(CONCAT(?ns, 'vak/', ?key)) AS ?concept)

    BIND (ENCODE_FOR_URI(LCASE(REPLACE(?e, " ", "-"))) AS ?vak_graad)
    BIND (URI(CONCAT(?ns, 'structuur/', ?vak_graad)) AS ?graad)

    BIND (ENCODE_FOR_URI(LCASE(REPLACE(?f, " ", "-"))) AS ?vak_thema)
    BIND (URI(CONCAT(?ns, 'thema/', ?vak_thema)) AS ?thema)
}
OFFSET 1
